import 'package:easy_localization/easy_localization.dart';
import '../models/Categorypro.dart';
import '../models/category.dart';
import 'colors.dart';

final List<Category> others = [];
final List<Categorypro> otherspro = [];
final List<Category> reptiles = [];
final List<Categorypro> reptilespro = [];
final List<Category> animalsfinal = [
  Category(
    'dogsandpuppies'.tr(),
    'assets/images/dog.svg',
    kAccentGreen,
  ),
  Category(
    'birds'.tr(),
    'assets/images/bird.svg',
    kAccentPurple,
  ),
  Category(
    'cats'.tr(),
    'assets/images/cat.svg',
    kAccentPurple,
  ),
  Category(
    'reptiles'.tr(),
    'assets/images/turtle.svg',
    kAccentPurple,
  ),
];
final List<Categorypro> animalsfinalpro = [
  Categorypro(
    'dogsandpuppies',
    'assets/images/dog.svg',
    kAccentGreen,
  ),
  Categorypro(
    'birds',
    'assets/images/bird.svg',
    kAccentPurple,
  ),
  Categorypro(
    'cats',
    'assets/images/cat.svg',
    kAccentPurple,
  ),
  Categorypro(
    'reptiles',
    'assets/images/turtle.svg',
    kAccentPurple,
  ),
];

final List<Category> dogsandpuppies = [
  Category(
    'germansphepherd'.tr(),
    'assets/images/new/animals/german.jpeg',
    kAccentGreen,
  ),
  Category(
    'siverianhusky'.tr(),
    'assets/images/new/animals/siverian.jpeg',
    kAccentPurple,
  ),
  Category(
    'americanpitbullterrior'.tr(),
    'assets/images/new/animals/pitbull.jpg',
    kAccentPurple,
  ),
  Category(
    'rottweiler'.tr(),
    'assets/images/new/animals/rotterwieler.jpeg',
    kAccentPurple,
  ),
  Category(
    'boerboel'.tr(),
    'assets/images/new/animals/boer.jpeg',
    kAccentPurple,
  ),
];
final List<Categorypro> dogsandpuppiespro = [
  Categorypro(
    'germansphepherd',
    'assets/images/new/animals/german.jpg',
    kAccentGreen,
  ),
  Categorypro(
    'siverianhusky',
    'assets/images/new/animals/siverian.jpeg',
    kAccentPurple,
  ),
  Categorypro(
    'americanpitbullterrior',
    'assets/images/new/animals/pitbull.jpg',
    kAccentPurple,
  ),
  Categorypro(
    'rottweiler',
    'assets/images/new/animals/rotterwieler.jpeg',
    kAccentPurple,
  ),
  Categorypro(
    'boerboel',
    'assets/images/new/animals/boer.jpeg',
    kAccentPurple,
  ),
];

final List<Category> birds = [
  Category(
    'pigeon'.tr(),
    'assets/images/new/animals/pigeon.svg',
    kAccentGreen,
  ),
  Category(
    'parrot'.tr(),
    'assets/images/new/animals/parrot.svg',
    kAccentGreen,
  ),
  Category(
    'eagle'.tr(),
    'assets/images/new/animals/eagle.svg',
    kAccentPurple,
  ),
  Category(
    'canary'.tr(),
    'assets/images/new/animals/canary.svg',
    kAccentPurple,
  ),
  Category(
    'crow'.tr(),
    'assets/images/new/animals/crow.svg',
    kAccentPurple,
  ),
  Category(
    'falcon'.tr(),
    'assets/images/new/animals/falcon.svg',
    kAccentPurple,
  ),
  Category(
    'fincnh'.tr(),
    'assets/images/new/animals/finch.svg',
    kAccentPurple,
  ),
];
final List<Categorypro> birdspro = [
  Categorypro(
    'pigeon',
    'assets/images/new/animals/pigeon.svg',
    kAccentGreen,
  ),
  Categorypro(
    'parrot',
    'assets/images/new/animals/parrot.svg',
    kAccentGreen,
  ),
  Categorypro(
    'eagle',
    'assets/images/new/animals/eagle.svg',
    kAccentPurple,
  ),
  Categorypro(
    'canary',
    'assets/images/new/animals/canary.svg',
    kAccentPurple,
  ),
  Categorypro(
    'crow',
    'assets/images/new/animals/crow.svg',
    kAccentPurple,
  ),
  Categorypro(
    'falcon',
    'assets/images/new/animals/falcon.svg',
    kAccentPurple,
  ),
  Categorypro(
    'fincnh',
    'assets/images/new/animals/finch.svg',
    kAccentPurple,
  ),
];

final List<Category> cats = [
  Category(
    'americancurl'.tr(),
    'assets/images/new/animals/americancurl.jpg',
    kAccentGreen,
  ),
  Category(
    'americanwirehair'.tr(),
    'assets/images/new/animals/americanwirehair.jpg',
    kAccentPurple,
  ),
  Category(
    'britishshorthair'.tr(),
    'assets/images/new/animals/britishshorthair.jpg',
    kAccentPurple,
  ),
  Category(
    'mainecoon'.tr(),
    'assets/images/new/animals/mainecoon.jpg',
    kAccentPurple,
  ),
  Category(
    'persian'.tr(),
    'assets/images/new/animals/persian.jpg',
    kAccentPurple,
  ),
  Category(
    'fincnhcat'.tr(),
    'assets/images/new/animals/finch1.jpeg',
    kAccentPurple,
  ),
  Category(
    'americanshorthair'.tr(),
    'assets/images/new/animals/americanshorthair.jpeg',
    kAccentPurple,
  ),
];
final List<Categorypro> catspro = [
  Categorypro(
    'americancurl',
    'assets/images/new/animals/americancurl.jpg',
    kAccentGreen,
  ),
  Categorypro(
    'americanwirehair',
    'assets/images/new/animals/americanwirehair.jpg',
    kAccentPurple,
  ),
  Categorypro(
    'britishshorthair',
    'assets/images/new/animals/britishshorthair.jpg',
    kAccentPurple,
  ),
  Categorypro(
    'mainecoon',
    'assets/images/new/animals/mainecoon.jpg',
    kAccentPurple,
  ),
  Categorypro(
    'persian',
    'assets/images/new/animals/persian.jpg',
    kAccentPurple,
  ),
  Categorypro(
    'fincnh',
    'assets/images/new/animals/finch1.jpeg',
    kAccentPurple,
  ),
  Categorypro(
    'americanshorthair',
    'assets/images/new/animals/americanshorthair.jpeg',
    kAccentPurple,
  ),
];
