
import 'package:easy_localization/easy_localization.dart';

import '../models/Categorypro.dart';
import '../models/category.dart';
import 'colors.dart';

final List<Category> mobileaccessory = [
  Category(
    'Power bank'.tr(),
    'assets/images/new/mobileandtablets/powerbank.svg',
    kAccentGreen,
  ),
  Category(
    'Cases'.tr(),
    'assets/images/new/mobileandtablets/case.svg',
    kAccentPurple,
  ),
  Category(
    'Chargersandpoweradapters'.tr(),
    'assets/images/new/mobileandtablets/charger.svg',
    kAccentPurple,
  ),
  Category(
    'Phonescreens'.tr(),
    'assets/images/new/mobileandtablets/screen.svg',
    kAccentYellow,
  ),
  Category(
    'Bluetoothheadsets'.tr(),
    'assets/images/new/mobileandtablets/headset.svg',
    kAccentPurple,
  ),
    Category(
    'screencovers'.tr(),
    'assets/images/new/mobileandtablets/screencover.svg',
    kAccentPurple,
  ),
];
final List<Categorypro> mobileaccessorypro = [
   Categorypro(
    'Power bank',
    'assets/images/new/mobileandtablets/powerbank.svg',
    kAccentGreen,
  ),
  Categorypro(
    'Cases',
    'assets/images/new/mobileandtablets/case.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Chargersandpoweradapters',
    'assets/images/new/mobileandtablets/charger.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Phonescreens',
    'assets/images/new/mobileandtablets/screen.svg',
    kAccentYellow,
  ),
  Categorypro(
    'Bluetoothheadsets',
    'assets/images/new/mobileandtablets/headset.svg',
    kAccentPurple,
  ),
    Categorypro(
    'screencovers',
    'assets/images/new/mobileandtablets/screencover.svg',
    kAccentPurple,
  ),
];
final List<Category> smartwatches = [
  Category(
    'Samsung'.tr(),
    'assets/images/samsung.svg',
    kAccentGreen,
  ),
  Category(
    'Apple'.tr(),
    'assets/images/apple.svg',
    kAccentPurple,
  ),
  Category(
    'Xiaomi'.tr(),
    'assets/images/xiaomi.svg',
    kAccentPurple,
  ),
  Category(
    'Honor'.tr(),
    'assets/images/huawei.svg',
    kAccentYellow,
  ),
  Category(
    'Acer'.tr(),
    'assets/images/new/mobileandtablets/acer.svg',
    kAccentPurple,
  ),
    Category(
    'Amazfit'.tr(),
    'assets/images/new/mobileandtablets/amazfit.svg',
    kAccentPurple,
  ),

];
final List<Categorypro> smartwatchespro = [
   Categorypro(
    'Samsung',
    'assets/images/samsung.svg',
    kAccentGreen,
  ),
  Categorypro(
    'Apple',
    'assets/images/apple.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Xiaomi',
    'assets/images/xiaomi.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Honor',
    'assets/images/huawei.svg',
    kAccentYellow,
  ),
  Categorypro(
    'Acer',
    'assets/images/new/mobileandtablets/acer.svg',
    kAccentPurple,
  ),
    Categorypro(
    'Amazfit',
    'assets/images/new/mobileandtablets/amazfit.svg',
    kAccentPurple,
  ),
];

final List<Category> tablets = [
  Category(
    'Samsung'.tr(),
    'assets/images/samsung.svg',
    kAccentGreen,
  ),
  Category(
    'Apple'.tr(),
    'assets/images/apple.svg',
    kAccentPurple,
  ),
  Category(
    'Lenovo'.tr(),
    'assets/images/lenovo.svg',
    kAccentPurple,
  ),
  Category(
    'Huawei'.tr(),
    'assets/images/huawei.svg',
    kAccentYellow,
  ),
  Category(
    'Amazon'.tr(),
    'assets/images/logo-amazon.svg',
    kAccentPurple,
  ),

    Category(
    'Modio'.tr(),
    'assets/images/modio.svg',
    kAccentPurple,
  ),

];
final List<Categorypro> tabletspro = [
   Categorypro(
    'Samsung',
    'assets/images/samsung.svg',
    kAccentGreen,
  ),
  Categorypro(
    'Apple',
    'assets/images/apple.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Lenovo',
    'assets/images/lenovo.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Huawei',
    'assets/images/huawei.svg',
    kAccentYellow,
  ),
  Categorypro(
    'Amazon',
    'assets/images/logo-amazon.svg',
    kAccentPurple,
  ),

    Categorypro(
    'Modio',
    'assets/images/modio.svg',
    kAccentPurple,
  ),

];
final List<Category> phone = [
  Category(
    'Samsung'.tr(),
    'assets/images/samsung.svg',
    kAccentGreen,
  ),
  Category(
    'iphone'.tr(),
    'assets/images/apple.svg',
    kAccentPurple,
  ),
  Category(
    'Nokia'.tr(),
    'assets/images/nokia.svg',
    kAccentPurple,
  ),
  Category(
    'Huawei'.tr(),
    'assets/images/huaweipro.svg',
    kAccentYellow,
  ),
  Category(
    'Xiaomi'.tr(),
    'assets/images/xiaomi.svg',
    kAccentPurple,
  ),
];
final List<Categorypro> phonepro = [
  Categorypro(
    'Samsung',
    'assets/images/samsung.svg',
    kAccentGreen,
  ),
  Categorypro(
    'iphone',
    'assets/images/apple.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Nokia',
    'assets/images/nokia.svg',
    kAccentPurple,
  ),
  Categorypro(
    'Huawei',
    'assets/images/huaweipro.svg',
    kAccentYellow,
  ),
  Categorypro(
    'Xiaomi',
    'assets/images/xiaomi.svg',
    kAccentPurple,
  ),
];
final List<Category> mobileandtablets = [
  Category(
    'phone'.tr(),
    'assets/images/phone.svg',
    kAccentGreen,
  ),
  Category(
    'tablets'.tr(),
    'assets/images/new/mobileandtablets/tablet.svg',
    kAccentGreen,
  ),
  Category(
    'smartwatches'.tr(),
    'assets/images/watch.svg',
    kAccentPurple,
  ),
  Category(
    'mobileaccessory'.tr(),
    'assets/images/new/mobileandtablets/charget.svg',
    kAccentPurple,
  ),
];



final List<Categorypro> mobileandtabletspro = [
    Categorypro(
    'phone',
    'assets/images/phone.svg',
    kAccentGreen,
  ),
  Categorypro(
    'tablets',
    'assets/images/new/mobileandtablets/tablet.svg',
    kAccentGreen,
  ),
  Categorypro(
    'smartwatches',
    'assets/images/watch.svg',
    kAccentPurple,
  ),
  Categorypro(
    'mobileaccessory',
    'assets/images/new/mobileandtablets/charget.svg',
    kAccentPurple,
  ),
];
